[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[site]
  title = "MAVRIDIS - Constructions & Architectural Services"
  description = "MAVRIDIS - Constructions & Architectural Services"